/* See COPYRIGHT for copyright information. */

#include <inc/x86.h>
#include <inc/mmu.h>
#include <inc/error.h>
#include <inc/string.h>
#include <inc/assert.h>

#include <kern/pmap.h>
#include <kern/kclock.h>
#include <kern/env.h>

// These variables are set by i386_detect_memory()
size_t npages;			// Amount of physical memory (in pages)
static size_t npages_basemem;	// Amount of base memory (in pages)

// These variables are set in mem_init()
pde_t *kern_pgdir;		// Kernel's initial page directory
struct PageInfo *pages;		// Physical page state array

// this is an LL of the free available pages
static struct PageInfo *page_free_list;	// Free list of physical pages


// --------------------------------------------------------------
// Detect machine's physical memory setup.
// --------------------------------------------------------------

static int
nvram_read(int r)
{
	return mc146818_read(r) | (mc146818_read(r + 1) << 8);
}

static void
i386_detect_memory(void)
{
	size_t basemem, extmem, ext16mem, totalmem;

	// Use CMOS calls to measure available base & extended memory.
	// (CMOS calls return results in kilobytes.)
	basemem = nvram_read(NVRAM_BASELO);
	extmem = nvram_read(NVRAM_EXTLO);
	ext16mem = nvram_read(NVRAM_EXT16LO) * 64;

	// Calculate the number of physical pages available in both base
	// and extended memory.
	if (ext16mem)
		totalmem = 16 * 1024 + ext16mem;
	else if (extmem)
		totalmem = 1 * 1024 + extmem;
	else
		totalmem = basemem;

	npages = totalmem / (PGSIZE / 1024);
	npages_basemem = basemem / (PGSIZE / 1024);

	cprintf("Physical memory: %uK available, base = %uK, extended = %uK\n",
		totalmem, basemem, totalmem - basemem);
}


// --------------------------------------------------------------
// Set up memory mappings above UTOP.
// --------------------------------------------------------------

static void boot_map_region(pde_t *pgdir, uintptr_t va, size_t size, physaddr_t pa, int perm);
static void check_page_free_list(bool only_low_memory);
static void check_page_alloc(void);
static void check_kern_pgdir(void);
static physaddr_t check_va2pa(pde_t *pgdir, uintptr_t va);
static void check_page(void);
static void check_page_installed_pgdir(void);

// This simple physical memory allocator is used only while JOS is setting
// up its virtual memory system.  page_alloc() is the real allocator.
//
// If n>0, allocates enough pages of contiguous physical memory to hold 'n'
// bytes.  Doesn't initialize the memory.  Returns a kernel virtual address.
//
// If n==0, returns the address of the next free page without allocating
// anything.
//
// If we're out of memory, boot_alloc should panic.
// This function may ONLY be used during initialization,
// before the page_free_list list has been set up.
static void *
boot_alloc(uint32_t n)
{
	static char *nextfree;	// virtual address of next byte of free memory
    char *new_nextfree;	    // virtual address of next byte of free memory
	char *prev_nextfree;	// virtual address of next byte of free memory
	char *result;

	// Initialize nextfree if this is the first time.
	// 'end' is a magic symbol automatically generated by the linker,
	// which points to the end of the kernel's bss segment:
	// the first virtual address that the linker did *not* assign
	// to any kernel code or global variables.
	if (!nextfree) {
		extern char end[];
		nextfree = ROUNDUP((char *) end + 1, PGSIZE);
       // cprintf("here is initial NEXTFREE: %p\n\n", nextfree);
       // cprintf("here is value NEXTFREE: %p\n\n", (void*)&nextfree);
	}


	// Allocate a chunk large enough to hold 'n' bytes, then update
	// nextfree.  Make sure nextfree is kept aligned
	// to a multiple of PGSIZE.
	//
	// LAB 2: Your code here.
    if (n == 0) {
        // panic("you have now reached n=0 in boot_alloc");
        return nextfree;
    } else if (n < 0) {
        panic("you attempted to boot_alloc with negative memory!");
    } else {
    	// Find out how much memory the machine has (npages & npages_basemem).
    	i386_detect_memory();
        if (npages <= 0 || (npages*4096) < n) {
            // panic if it turns out that there's not enuf phys mem for n bytes
            panic("there is not enough physical memory for this boot_alloc asking for %u bytes (%u pages) when there is %d pages available", n, n/4096, npages);
        }
        new_nextfree = ROUNDUP(nextfree + n, PGSIZE);
        prev_nextfree = nextfree;
        nextfree = new_nextfree;
        cprintf("prev node: %p, curr node: %p, n: %d\n\n", prev_nextfree, nextfree, n);
    	return prev_nextfree;
    }
}

// Set up a two-level page table:
//    kern_pgdir is its linear (virtual) address of the root
//
// This function only sets up the kernel part of the address space
// (ie. addresses >= UTOP).  The user part of the address space
// will be set up later.
//
// From UTOP to ULIM, the user is allowed to read but not write.
// Above ULIM the user cannot read or write.
void
mem_init(void)
{
	uint32_t cr0;
	size_t n;
    //struct PageInfo *pages;

	// Find out how much memory the machine has (npages & npages_basemem).
	i386_detect_memory();

	// Remove this line when you're ready to test this function.
	// panic("mem_init: This function is not finished\n");

	//////////////////////////////////////////////////////////////////////
	// create initial page directory.
	kern_pgdir = (pde_t *) boot_alloc(PGSIZE);
	memset(kern_pgdir, 0, PGSIZE);

	//////////////////////////////////////////////////////////////////////
	// Recursively insert PD in itself as a page table, to form
	// a virtual page table at virtual address UVPT.
	// (For now, you don't have understand the greater purpose of the
	// following line.)

	// Permissions: kernel R, user R
	kern_pgdir[PDX(UVPT)] = PADDR(kern_pgdir) | PTE_U | PTE_P;

	//////////////////////////////////////////////////////////////////////
	// Allocate an array of npages 'struct PageInfo's and store it in 'pages'.
	// The kernel uses this array to keep track of physical pages: for
	// each physical page, there is a corresponding struct PageInfo in this
	// array.  'npages' is the number of physical pages in memory.  Use memset
	// to initialize all fields of each struct PageInfo to 0.
	// Your code goes here:




// CODE_3
	//////////////////////////////////////////////////////////////////////
	// Make 'envs' point to an array of size 'NENV' of 'struct Env'.
	// LAB 3: Your code here.
    envs = boot_alloc(NENV * sizeof(struct Env));
    memset(envs, 0, NENV * sizeof(struct Env));
    // void boot_map_region(pde_t *pgdir, uintptr_t va, size_t size, physaddr_t pa, int perm)
// END_CODE_3



    // so first we allocate the num of bytes in the param below
    pages = boot_alloc(npages * sizeof(struct PageInfo));
    // sizeof(pages), sizeof(struct PageInfo), npages, 4, 4096
    // npages - npages_basemem (we don't want to reset the mem of our basemem)
    memset(pages, 0, npages * sizeof(struct PageInfo));

    // panic("memset has worked i think, now calling page_init()");



	//////////////////////////////////////////////////////////////////////
	// Now that we've allocated the initial kernel data structures, we set
	// up the list of free physical pages. Once we've done so, all further
	// memory management will go through the page_* functions. In
	// particular, we can now map memory using boot_map_region
	// or page_insert
	page_init();

	check_page_free_list(1);
	check_page_alloc();
	check_page();

	//////////////////////////////////////////////////////////////////////
	// Now we set up virtual memory

	//////////////////////////////////////////////////////////////////////
	// Map 'pages' read-only by the user at linear address UPAGES
	// Permissions:
	//    - the new image at UPAGES -- kernel R, user R
	//      (ie. perm = PTE_U | PTE_P)
	//    - pages itself -- kernel RW, user NONE
	// Your code goes here:

	//////////////////////////////////////////////////////////////////////
	// Map the 'envs' array read-only by the user at linear address UENVS
	// (ie. perm = PTE_U | PTE_P).
	// Permissions:
	//    - the new image at UENVS  -- kernel R, user R
	//    - envs itself -- kernel RW, user NONE
	// LAB 3: Your code here.
    //






    // boot-map-region is ONLY for addresses above UTOP
    // void boot_map_region(pde_t *pgdir, uintptr_t va, size_t size, physaddr_t pa, int perm)
    // int page_insert(pde_t *pgdir, struct PageInfo *pp, void *va, int perm)
        // returns 0 on success, and -E_NO_MEM on failure
    //cprintf("UPAGES:  %p\n\n", UPAGES);

	n = ROUNDUP(npages*sizeof(struct PageInfo), PGSIZE);
//	for (int i = 0; i < n; i += PGSIZE) {
//    //size_t numPages = sizeof(pages) / sizeof(pages[0]);
//    //for (i = 0; i <= numPages; i++) {
//        //boot_map_region(kern_pgdir, UPAGES, sizeof(pages), (physaddr_t)bootstack, PTE_U | PTE_P);
//        struct PageInfo *pp;
//        pp = page_alloc(0);
//        if (pp == NULL) {
//            panic("in mem_init, page_alloc for UPAGES failed");
//        }
//        cprintf("UPAGES: %p,  PADDR pages start: %p, pages[i]: %p\n\n", UPAGES, PADDR(pages), &pages[i]);
//        if (page_insert(kern_pgdir, &pages[i], (void *)(UPAGES + i), PTE_U | PTE_P) != 0) {
//            panic("in mem_init, page_insert for UPAGES failed");
//        }
//    }

    boot_map_region(kern_pgdir, UPAGES, n, PADDR(pages), PTE_U | PTE_P);

	//////////////////////////////////////////////////////////////////////
	// Use the physical memory that 'bootstack' refers to as the kernel
	// stack.  The kernel stack grows down from virtual address KSTACKTOP.
	// We consider the entire range from [KSTACKTOP-PTSIZE, KSTACKTOP)
	// to be the kernel stack, but break this into two pieces:
	//     * [KSTACKTOP-KSTKSIZE, KSTACKTOP) -- backed by physical memory
	//     * [KSTACKTOP-PTSIZE, KSTACKTOP-KSTKSIZE) -- not backed; so if
	//       the kernel overflows its stack, it will fault rather than
	//       overwrite memory.  Known as a "guard page".
	//     Permissions: kernel RW, user NONE
	// Your code goes here:

    // need to ALLOC PAGES
    boot_map_region(kern_pgdir, KSTACKTOP-KSTKSIZE, KSTKSIZE, PADDR(bootstack), PTE_W | PTE_P);
    //boot_map_region(kern_pgdir, KSTACKTOP-PTSIZE, KSTACKTOP-PTSIZE+KSTKSIZE, (physaddr_t)NULL, PTE_W | PTE_P);


//	// check kernel stack
//	for (i = 0; i < KSTKSIZE; i += PGSIZE)
//		assert(check_va2pa(pgdir, KSTACKTOP - KSTKSIZE + i) == PADDR(bootstack) + i);
//	assert(check_va2pa(pgdir, KSTACKTOP - PTSIZE) == ~0);


	//////////////////////////////////////////////////////////////////////
	// Map all of physical memory at KERNBASE.
	// Ie.  the VA range [KERNBASE, 2^32) should map to
	//      the PA range [0, 2^32 - KERNBASE)
	// We might not have 2^32 - KERNBASE bytes of physical memory, but
	// we just set up the mapping anyway.
	// Permissions: kernel RW, user NONE
	// Your code goes here:


    boot_map_region(kern_pgdir, KERNBASE, (uint32_t)0xFFFFFFFF - KERNBASE, 0x0, PTE_W | PTE_P);


// CODE_3
	n = ROUNDUP(NENV*sizeof(struct Env), PGSIZE);
    boot_map_region(kern_pgdir, UENVS, n, PADDR(envs), PTE_U | PTE_P);
// END_CODE_3



	// Check that the initial page directory has been set up correctly.
	check_kern_pgdir();

	// Switch from the minimal entry page directory to the full kern_pgdir
	// page table we just created.	Our instruction pointer should be
	// somewhere between KERNBASE and KERNBASE+4MB right now, which is
	// mapped the same way by both page tables.
	//
	// If the machine reboots at this point, you've probably set up your
	// kern_pgdir wrong.
	lcr3(PADDR(kern_pgdir));

	check_page_free_list(0);

	// entry.S set the really important flags in cr0 (including enabling
	// paging).  Here we configure the rest of the flags that we care about.
	cr0 = rcr0();
	cr0 |= CR0_PE|CR0_PG|CR0_AM|CR0_WP|CR0_NE|CR0_MP;
	cr0 &= ~(CR0_TS|CR0_EM);
	lcr0(cr0);

	// Some more checks, only possible after kern_pgdir is installed.
	check_page_installed_pgdir();
}

// --------------------------------------------------------------
// Tracking of physical pages.
// The 'pages' array has one 'struct PageInfo' entry per physical page.
// Pages are reference counted, and free pages are kept on a linked list.
// --------------------------------------------------------------

//
// Initialize page structure and memory free list.
// After this is done, NEVER use boot_alloc again.  ONLY use the page
// allocator functions below to allocate and deallocate physical
// memory via the page_free_list.
//
void
page_init(void)
{
	// The example code here marks all physical pages as free.
	// However this is not truly the case.  What memory is free?
	//  1) Mark physical page 0 as in use.
	//     This way we preserve the real-mode IDT and BIOS structures
	//     in case we ever need them.  (Currently we don't, but...)
	//  2) The rest of base memory, [PGSIZE, npages_basemem * PGSIZE)
	//     is free.
	//  3) Then comes the IO hole [IOPHYSMEM, EXTPHYSMEM), which must
	//     never be allocated.
	//  4) Then extended memory [EXTPHYSMEM, ...).
	//     Some of it is in use, some is free. Where is the kernel
	//     in physical memory?  Which pages are already in use for
	//     page tables and other data structures?
	//
	// Change the code to reflect this.
	// NB: DO NOT actually touch the physical memory corresponding to
	// free pages!
    //
    //
    // pages is an arr of struct PageInfo
    // pp_link is PageInfo's ptr to the next avail PageInfo page in the LL
    // pp_ref is a PageInfo's count of how many refs are using that phys page
    // NOTE: pp_ref only counts refs that were allocated with page_alloc(), and
    // refs allocated via boot_alloc() were already setup, and boot_alloc()
    // returned the next_free_page so this is where we start our free-page
    // structure
    //
    // leave a NULL node at the TAIL of the LL, so "page_free_list" will always
    // be the HEAD of the LL, and NULL will always be the tail of the LL, and
    // we will insert pages btw these always
    //
    //
    //
    // first we need to check (for all pages in the pages arr) which of these
    // pages are already being used by the Qs 1-4 above. So these pages's pp_ref
    // will be set to 1 if they are already in use, or set to 0 otherwise. You
    // will then have an arr of all pages with their appropriate reference num.
    // THEN, you use this code below (and you need to add in the if statement
    // which will check if page[i] has pp_ref=0 or not), to construct the LL
    // of avail phys pages (so only add a phys page to the LL if it is free)
    //
    //

    // panic("page_init() now starting");

    // the tail of page_free_list should be a NULL dummy node
   //  struct PageInfo tail;
   //  tail.pp_ref = 1;
   //  tail.pp_link = NULL;
   //  page_free_list = &tail;
    page_free_list = NULL;
	size_t i;
    unsigned long pages_init_bytes = (unsigned long)&pages - (unsigned long)KERNBASE;

	for (i = 0; i < npages; i++) {
        // if this page at i in the arr has no more refs, then put it at the
        // head of the LL. So we iterate thru all of the pages in the arr
        // to construct the LL
        // KERNBASE + 4MB is at 0xF4000000
        // cprintf("in page_init, idx is at i=%d\n\n", i);
        if (i == 0) {
            // cprintf("pages: %p\n\n", pages);
            pages[i].pp_ref = 1;
            // cprintf("page_init() page i=0 set");

        } else if (i < npages_basemem) {
		    pages[i].pp_ref = 0;
        } else if (i >= npages_basemem && i < npages_basemem + (384000/PGSIZE)) {
            // we are now at (npages_basemem * PGSIZE bytes)
            // and IOPHYSMEM to EXTPHYSMEM is a 384KB hole reserved for devices
            // and we need to divide this by PGSIZE to get the num of pages
		    pages[i].pp_ref = 1;
        } else if (i >= npages_basemem + (384000/PGSIZE) && i < npages_basemem + (384000/PGSIZE) + (size_t)(pages_init_bytes/PGSIZE)) {
            // we are now at 0x100000 hex and need to decide addresses above
            // this are already in use based on boot_alloc, etc.
            // so this is all phys mem above 1MB, this is where the kernel was
            // placed by mem_init, so now we have the next_free_page var which
            // was returned by boot_alloc and then set to *pages in mem_init
            // and everything from that page and above is free extmem
            //
            // the kernel is 4MB in size (KERNBASE + 4MB) so we need to divide
            // this by the PGSIZE to get the num of pages it uses up
            //
            // above the kernel is the struct PageInfo *pages arr which was
            // made by boot_alloc, but some of this was used, and so the next
            // available page is returned by boot_alloc and is stored by
            // mem_init in the pages* var. So everything btw the end of the
            // kernel and the address of *pages is being used
		    pages[i].pp_ref = 1;
        } else {
            // now all of the mem above the *pages var is free
		    pages[i].pp_ref = 0;
        }
        // now insert the pages that had no refs
        // we only insert curr phys page into the LL if it is free
        if (pages[i].pp_ref == 0) {
            // we always insert after the HEAD
            // so point this curr page to the HEAD.next
	    	pages[i].pp_link = page_free_list;
            // then move the HEAD pointer to now point at this new HEAD.next
	    	page_free_list = &pages[i];
        }
	}

    // cprintf("END OF PAGE_INIT:   here is page_free_list: %p and its value: %p, and its pp_link: %p\n\n", page_free_list, *page_free_list, page_free_list->pp_link);
    // cprintf("page_init() has worked i think, now leaving page_init()\n\n");
}

//
// Allocates a physical page.  If (alloc_flags & ALLOC_ZERO), fills the entire
// returned physical page with '\0' bytes.  Does NOT increment the reference
// count of the page - the caller must do these if necessary (either explicitly
// or via page_insert).
//
// Be sure to set the pp_link field of the allocated page to NULL so
// page_free can check for double-free bugs.
//
// Returns NULL if out of free memory.
//
// Hint: use page2kva and memset
struct PageInfo *
page_alloc(int alloc_flags)
{
	// Fill this function in

    // if out of FREE memory, the HEAD of the LL will point to the tail value NULL
    // cprintf("PAGE_ALLOC:   here is page_free_list: %p and its value: %p, and its pp_link: %p\n\n", page_free_list, *page_free_list, page_free_list->pp_link);
    if (page_free_list == NULL) {
        return NULL;
    }

    // cprintf("here is page_free_list: %p and its value: %p\n\n", page_free_list, *page_free_list);

    // remove the HEAD of the LL from page_free_list
    struct PageInfo *new_page = page_free_list;
    page_free_list = page_free_list->pp_link;
    new_page->pp_link = NULL;

    // set this page to 0's if these flags are true
    if (alloc_flags && ALLOC_ZERO == 1) {
	    memset(page2kva(new_page), 0, PGSIZE);
    } else {
	    // memset(page2kva(new_page), 0, PGSIZE);
        new_page->pp_ref = 0;
    }

   // cprintf("new_page pp_ref: %d", new_page->pp_ref);
   // cprintf("new_page pp_link: %p", new_page->pp_link);

	return new_page;
}

//
// Return a page to the free list.
// (This function should only be called when pp->pp_ref reaches 0.)
//
void
page_free(struct PageInfo *pp)
{
	// Fill this function in
	// Hint: You may want to panic if pp->pp_ref is nonzero or
	// pp->pp_link is not NULL.
    // cprintf("START OF PAGE FREE:   PPPPPPPPP: %p and its value: %p, and its pp_ref: %d, and its pp_link: %p\n\n", pp, *pp, pp->pp_ref, pp->pp_link);
    if (pp->pp_ref != 0 || pp->pp_link != NULL) {
        panic("in page_free but this page either has a ref count > 0 or it has a non-NULL next pointer");
    } else {
        pp->pp_link = page_free_list;
    // cprintf("IN PAGE FREE:   here is page_free_list: %p and its value: %p, and its pp_link: %p\n\n", page_free_list, *page_free_list, page_free_list->pp_link);
    // cprintf("here is PAGE FREE pp: %p, and the values at its pp_ref: %d, and its pp_link: %p\n\n", pp, pp->pp_ref, pp->pp_link);
        page_free_list = pp;
    // cprintf("IN PAGE FREE 2:   here is page_free_list: %p and its value: %p, and its pp_link: %p\n\n", page_free_list, *page_free_list, page_free_list->pp_link);
    // cprintf("here is PAGE FREE pp: %p, and the values at its pp_ref: %d, and its pp_link: %p\n\n", pp, pp->pp_ref, pp->pp_link);
    }

}

//
// Decrement the reference count on a page,
// freeing it if there are no more refs.
//
void
page_decref(struct PageInfo* pp)
{
	if (--pp->pp_ref == 0)
		page_free(pp);
}

// Given 'pgdir', a pointer to a page directory, pgdir_walk returns
// a pointer to the page table entry (PTE) for linear address 'va'.
// This requires walking the two-level page table structure.
//
// The relevant page table page might not exist yet.
// If this is true, and create == false, then pgdir_walk returns NULL.
// Otherwise, pgdir_walk allocates a new page table page with page_alloc.
//    - If the allocation fails, pgdir_walk returns NULL.
//    - Otherwise, the new page's reference count is incremented,
//	the page is cleared,
//	and pgdir_walk returns a pointer into the new page table page.
//
// Hint 1: you can turn a PageInfo * into the physical address of the
// page it refers to with page2pa() from kern/pmap.h.
//
// Hint 2: the x86 MMU checks permission bits in both the page directory
// and the page table, so it's safe to leave permissions in the page
// directory more permissive than strictly necessary.
//
// Hint 3: look at inc/mmu.h for useful macros that manipulate page
// table and page directory entries.
//
pte_t *
pgdir_walk(pde_t *pgdir, const void *va, int create)
{
	// Fill this funtion in
    //
    // we are using va to find our page table entry
    // first we will use the first 10 bits of va to get the idx into the page dir
    // then we use the next 10 bits to get the page table entry in that page dir
    // and that is what this func returns, so it took in a va and returned the
    // associated pa (a pointer to it) via the page tables
    //
    // so we use virtual addresses to get to the entry in the page dir/tables,
    // and then the entry itself is the pa
    //

    // get first 10 bits via PDX macro, then get PDE by indexing this info in
    // the pgdir[] arr
    pde_t pde = pgdir[PDX(va)];

    //  cprintf("pgdir_walk, here is pde&PTE_P: %d, here is create: %d, and here is both: %d\n\n", pde&PTE_P, create, pde&PTE_P && create);
    // if the page table DNE and we are not creating a page, then return NULL
    if (!pde&PTE_P && !create) {
	    return NULL;
    } else if (pde&PTE_P) {
        // page is valid and we are NOT creating it
        // so we grab this page from the page table entry, but this is a phys
        // address, so we also need to convert it so that the kernel can actually
        // use it
        // cprintf("in pgdir_walk, returning exisiting page\n\n");
        pte_t *page_table = (pte_t *)KADDR(PTE_ADDR(pde));
        // and now we have the page table, and we will idx into it to get the
        // exact entry in that table we want, and since we are returning a ptr
        // to that entry then we use & also
        return &page_table[PTX(va)];
    } else if (!pde&PTE_P && create) {
        // we are creating the page table
        // so first we alloc a new page
        // cprintf("in pgdir_walk, creating new page\n\n");
        struct PageInfo *pp_page_table = page_alloc(1);
        // if there are no more free pages left, page_alloc returns NULL
        if (pp_page_table == NULL) {
            return NULL;
        }
        // be sure to increment the pp_ref of that table now
        pp_page_table->pp_ref += 1;
        // and now we need to set this page table in the page dir
        // and this is a Phys address, so we convert from virtual
        pgdir[PDX(va)] = page2pa(pp_page_table) | PTE_P | PTE_U | PTE_W;
        // and we return a ptr to that entry holding the phys address
        pde_t pde = pgdir[PDX(va)];
        pte_t *page_table = (pte_t *)KADDR(PTE_ADDR(pde));
        return &page_table[PTX(va)];
    }
    // cprintf("in pgdir_walk, this should NEVER print, you are calling pgdir_walk with both a valid page and with the create flag set\n\n");
    return NULL;
}

//
// Map [va, va+size) of virtual address space to physical [pa, pa+size)
// in the page table rooted at pgdir.  Size is a multiple of PGSIZE, and
// va and pa are both page-aligned.
// Use permission bits perm|PTE_P for the entries.
//
// This function is only intended to set up the ``static'' mappings
// above UTOP. As such, it should *not* change the pp_ref field on the
// mapped pages.
//
// Hint: the TA solution uses pgdir_walk
static void
boot_map_region(pde_t *pgdir, uintptr_t va, size_t size, physaddr_t pa, int perm)
{
	// Fill this function in
    //
    // for the regions of virtual space that map to important OS tools, we
    // want the mapping into physical space to be contiguous
    //
    // and these parts of the mapping are NOT a part of our FREE LL mem, so
    // we do not increment pp_ref for these cuz these pages are never avialable
    // for use by user programs

    // for each table in size/PGSIZE, we create that table in the given pgdir
    // and we set its entry as given pa with perm permissions
    for (int i = 0; i < size/PGSIZE; i++) {
        const void *next_va = (const void*)(va + (i * PGSIZE));
        pte_t* pa_entry_ptr = pgdir_walk(pgdir, next_va, 1);
        if (pa_entry_ptr == NULL) {
            panic("in boot_map_region, pgdir_walk has returned NULL for the page table entry at i*PGSIZE = %d and next_va of %p\n\n", i*PGSIZE, next_va);
        }
        *pa_entry_ptr = (pa + (i * PGSIZE)) | perm | PTE_P;
        // may need to convert pa from va to pa (it may not be a pa)
        // pa_entry_ptr += (i * PGSIZE);
        // set the value at that page table entry to the next_pa
        // may need to change pp_link here also
        // *pa_entry_ptr = *next_pa;
        // set the permissions at that page table entry
        // pgdir[PDX(next_va)] = *pa_entry_ptr | perm | PTE_P;
    }

}

//
// Map the physical page 'pp' at virtual address 'va'.
// The permissions (the low 12 bits) of the page table entry
// should be set to 'perm|PTE_P'.
//
// Requirements
//   - If there is already a page mapped at 'va', it should be page_remove()d.
//   - If necessary, on demand, a page table should be allocated and inserted
//     into 'pgdir'.
//   - pp->pp_ref should be incremented if the insertion succeeds.
//   - The TLB must be invalidated if a page was formerly present at 'va'.
//
// Corner-case hint: Make sure to consider what happens when the same
// pp is re-inserted at the same virtual address in the same pgdir.
// However, try not to distinguish this case in your code, as this
// frequently leads to subtle bugs; there's an elegant way to handle
// everything in one code path.
//
// RETURNS:
//   0 on success
//   -E_NO_MEM, if page table couldn't be allocated
//
// Hint: The TA solution is implemented using pgdir_walk, page_remove,
// and page2pa.
//


int
page_insert(pde_t *pgdir, struct PageInfo *pp, void *va, int perm)
{

    //cprintf("IN PAGE INSERT: here is to-be-inserted page: %p, and it's value: %p, and pp_ref: %d, and pp_link: %p\n\n", pp, *pp, pp->pp_ref, pp->pp_link);
    //cprintf("PAGE INSERT, page_free_list: %p, pp_ref: %d, pp_link: %p\n\n", page_free_list, page_free_list->pp_ref, page_free_list->pp_link);
    // first remove the pa that this va is already mapped to if there is one
    // if there isn't one, page_remove does nothing
    //cprintf("PAGE INSERT    VA    %p\n\n", va);
    //cprintf("PAGE INSERT    Page    %p,   page2pa   %p\n\n", pp, page2pa(pp));
    // page_remove(pgdir, va);
    // get the pa that the input wants to map this va to
    physaddr_t pa = page2pa(pp);
    // get the PTE at this va, or create one if this va has no mapping already
    pte_t *p_pte = pgdir_walk(pgdir, va, 1);
    //cprintf("JUST REMOVED new pa: %p, and old pa: %p, and pte: %p\n\n", pa, PTE_ADDR(*p_pte), p_pte);
    if (p_pte == NULL) {
        // either the va given to pgdir walk DNE or out of mem
        return -E_NO_MEM;
    } else if (PTE_ADDR(*p_pte) == pa) {
        // the pa in the pp that was just mapped to va was already mapped to
        // this va, so we don't add this mapping and just return, but we still
        // want to be able to change perms without increasing the ref count
        *p_pte = PTE_ADDR(page2pa(pp)) | perm | PTE_P;
        return 0;
    } else if (*p_pte & PTE_P) {
        // this va is already mapped to another pa, so that pa should first be
        // removed from this va. Cuz a va cannot map to multiple pa's
        // struct PageInfo *old_page = pa2page(PTE_ADDR(*p_pte));
        //void *old_va = page2kva(old_page);
        //cprintf("old va: %p\n\n", old_va);
        page_remove(pgdir, va);
        // old_page->pp_ref -= 1;
        //*p_pte = 0;
        // page_decref(old_page);
        //tlb_invalidate(pgdir, va);
    }

    // we get the pa pointed to by the page-pointer pp via page2pa(pp)
    // and we use this to point our p_pte pointer to this pa, along with
    // the permissions
    *p_pte = PTE_ADDR(page2pa(pp)) | perm | PTE_P;
    pp->pp_ref += 1;
    return 0;

}


//int
//page_insert(pde_t *pgdir, struct PageInfo *pp, void *va, int perm)
//{
//	// Fill this function in
//
//    cprintf("PAGE_INSERT_START:   pp: %p *pp: %p, pp->pp_link: %p\n\n", pp, *pp, pp->pp_link);
//    // we get the pa pointed to by the page-pointer pp via page2pa(pp)
//    physaddr_t pa = page2pa(pp);
//    // get a pointer to the PTE of that va using pgdir_walk, but first
//    // we try this w/o the "create" param, and if this returns NULL, then we
//    // know there was not already a pa mapped to this va
//    pte_t *p_pte = pgdir_walk(pgdir, va, 0);
//    if (p_pte != NULL) {
//        cprintf("new pa: %p, and old pa: %p, and pte: %p\n\n", pa, PTE_ADDR(*p_pte), p_pte);
//        // there is already a pa at this va, so un-map it
//        // But if the pa that the va is already mapped to
//        // is the same pa from given pp, then, do nothing
//        if (PTE_ADDR(*p_pte) == pa) {
//            cprintf("page_insert was given a pa that is already mapped to this va\n");
//            // the va is being mapped to the pa it is already mapped to, so we
//            // don't need to do anything
//            return 0;
//        } else {
//            cprintf("page_insert was given a new pa, this va is removing the mapping to its old pa\n");
//            // the va is being mapped to a new pa, so un-map this old pa
//            page_remove(pgdir, va);
//        }
//    }
//
//    // there is now no pa already at this va, so run pgdir_walk with the
//    // create param set this time so the entry is created
//    // cprintf("here is value at p_pte: %p, and it's own address: %p\n\n", *p_pte, p_pte);
//    p_pte = pgdir_walk(pgdir, va, 1);
//    // cprintf("here is value at p_pte: %p, and it's own address: %p\n\n", *p_pte, p_pte);
//    // but pgdir_walk will also return NULL if there are no more free pages,
//    // so if we are out of mem, then return E_NO_MEM
//    if (p_pte == NULL) {
//        // cprintf("returning E_NO_MEM\n\n");
//        return -E_NO_MEM;
//    }
//
//    // we get the pa pointed to by the page-pointer pp via page2pa(pp)
//    // and we use this to point our p_pte pointer to this pa, along with
//    // the permissions
//    *p_pte = PTE_ADDR(page2pa(pp)) | perm | PTE_P;
//    pp->pp_ref += 1;
//    // we only need the pp_link when this page is in the LL
//    pp->pp_link = NULL;
//
//    // cprintf("at end of page_insert()");
//    return 0;
//
//}

//
// Return the page mapped at virtual address 'va'.
// If pte_store is not zero, then we store in it the address
// of the pte for this page.  This is used by page_remove and
// can be used to verify page permissions for syscall arguments,
// but should not be used by most callers.
//
// Return NULL if there is no page mapped at va.
//
// Hint: the TA solution uses pgdir_walk and pa2page.
//
struct PageInfo *
page_lookup(pde_t *pgdir, void *va, pte_t **pte_store)
{
	// Fill this function in
    //
    // return the pa page mapped to va and store it in pte_store

    // storing into pte_store:
    // first get the ptr to the entry
    pte_t *p_pte = pgdir_walk(pgdir, va, 0);
    if (p_pte == NULL) {
        // if no pa page is mapped at this va, return NULL
        return NULL;
    }
    // then store it
    if (pte_store != NULL) {
        *pte_store = p_pte;
    }
    //  and return the page we found at va, which is a struct PageInfo

    // cprintf("at end of page_lookup()");
    return pa2page(PTE_ADDR(*p_pte));

}

//
// Unmaps the physical page at virtual address 'va'.
// If there is no physical page at that address, silently does nothing.
//
// Details:
//   - The ref count on the physical page should decrement.
//   - The physical page should be freed if the refcount reaches 0.
//   - The pg table entry corresponding to 'va' should be set to 0.
//     (if such a PTE exists)
//   - The TLB must be invalidated if you remove an entry from
//     the page table.
//
// Hint: The TA solution is implemented using page_lookup,
// 	tlb_invalidate, and page_decref.
//
void
page_remove(pde_t *pgdir, void *va)
{
	// Fill this function in

    pte_t *p_pte;
    struct PageInfo *pp = page_lookup(pgdir, va, &p_pte);
    //cprintf("PAGE REMOVE    VA    %p\n\n", va);
    //cprintf("PAGE REMOVE    Page    %p\n\n,   page2pa   %p\n\n", pp, page2pa(pp));
    //cprintf("PAGE REMOVE    pte_addr   %p\n\n", PTE_ADDR(*p_pte));
    // if the va was valid and there was a pa at that va, then
    // we now have the PTE where it was (in p_pte) and the pa itself in *pp
    // otherwise, there was no pa and this func does nothing
     //cprintf("IN PAGE REMOVE: here is to-be-removed page: %p, and it's value: %p, and pp_ref: %d, and pp_link: %p\n\n", pp, *pp, pp->pp_ref, pp->pp_link);
     if (!pp) {
         cprintf("PAGE REMOVE: the va is not mapped to any pa, no removal taking place\n");
         return;
     }
    //cprintf("PAGE_REMOVE BEFORE PAGE_FREE:   here is page_free_list: %p and its value: %p, and its pp_ref: %d, and its pp_link: %p\n\n", page_free_list, *page_free_list, page_free_list->pp_ref, page_free_list->pp_link);
    // now we un-map this page by setting the PTE to 0
    *p_pte = 0;
    // and we need to decrement the pp_ref
    page_decref(pp);
    // and if that pa now has a pp_ref of 0, then it should be freed so that
    // it can go back to the LL of free pages
   //  if (pp->pp_ref == 0) {
   //      page_free(pp);
   //  }
     //cprintf("IN PAGE REMOVE: here is was-removed page: %p, and it's value: %p, and pp_ref: %d, and pp_link: %p\n\n", pp, *pp, pp->pp_ref, pp->pp_link);
    //cprintf("PAGE_REMOVE AFTER PAGE_FREE:   here is page_free_list: %p and its value: %p, and its pp_ref: %d, and its pp_link: %p\n\n", page_free_list, *page_free_list, page_free_list->pp_ref, page_free_list->pp_link);
    // and we need to invalidate the TLB (this just removes the va from
    // the cache)
    tlb_invalidate(pgdir, va);

    // cprintf("at end of page_remove()");
}

//
// Invalidate a TLB entry, but only if the page tables being
// edited are the ones currently in use by the processor.
//
void
tlb_invalidate(pde_t *pgdir, void *va)
{
	// Flush the entry only if we're modifying the current address space.
	// For now, there is only one address space, so always invalidate.
	invlpg(va);
}

static uintptr_t user_mem_check_addr;

//
// Check that an environment is allowed to access the range of memory
// [va, va+len) with permissions 'perm | PTE_P'.
// Normally 'perm' will contain PTE_U at least, but this is not required.
// 'va' and 'len' need not be page-aligned; you must test every page that
// contains any of that range.  You will test either 'len/PGSIZE',
// 'len/PGSIZE + 1', or 'len/PGSIZE + 2' pages.
//
// A user program can access a virtual address if (1) the address is below
// ULIM, and (2) the page table gives it permission.  These are exactly
// the tests you should implement here.
//
// If there is an error, set the 'user_mem_check_addr' variable to the first
// erroneous virtual address.
//
// Returns 0 if the user program can access this range of addresses,
// and -E_FAULT otherwise.
//
int
user_mem_check(struct Env *env, const void *va, size_t len, int perm)
{
	// LAB 3: Your code here.

// CODE_3
        // we first need to check if the va itself is a valid page at all
        pte_t *pp = pgdir_walk(env->env_pgdir, va, 0);
        if (!pp) {
            // pgdir_walk returns NULL if the page is invalid or not in the given pgdir
            user_mem_check_addr = (uint32_t)va;
            //cprintf("in user_mem_check, the va that the user env is trying to access does not exist in the env_pgdir");
            return -E_FAULT;
        } else if ((*pp & perm) != perm) {
            // the page entry is a valid page in the env_pgdir but this page is blocked by the page table
            // so the user env does not have permission to access this page
            user_mem_check_addr = (uint32_t)va;
            //cprintf("in user_mem_check, the va that the user env is trying to access exists in the env_pgdir but the page table is not giving the user env permissions to access this page");
            return -E_FAULT;
        }


    // we are using this func to prevent a user program from accessing
    // kernel-level memory
    for (int i = (uint32_t) ROUNDUP(va, PGSIZE); i < (uint32_t) ROUNDUP(va+len, PGSIZE); i += PGSIZE) {
        pte_t *pp = pgdir_walk(env->env_pgdir, (void *) i, 0);
        // ULIM is the LOWER bound on the valid user program space, so we first check if
        // the curr va at i is a lower address than ULIM
        if (i < ULIM) {
            user_mem_check_addr = i;
            //cprintf("in user_mem_check, the va that the user env is trying to access is below the user space limit at ULIM");
            return -E_FAULT;
        } else if (!pp) {
            // pgdir_walk returns NULL if the page is invalid or not in the given pgdir
            user_mem_check_addr = i;
            //cprintf("in user_mem_check, the va that the user env is trying to access does not exist in the env_pgdir");
            return -E_FAULT;
        } else if ((*pp & perm) != perm) {
            // the page entry is a valid page in the env_pgdir but this page is blocked by the page table
            // so the user env does not have permission to access this page
            user_mem_check_addr = i;
            //cprintf("in user_mem_check, the va that the user env is trying to access exists in the env_pgdir but the page table is not giving the user env permissions to access this page");
            return -E_FAULT;
        }
    }
    // the user env is allowed to access the entire range of mem from va to va+len,
    // so we return 0 for success
// END_CODE_3

	return 0;
}

//
// Checks that environment 'env' is allowed to access the range
// of memory [va, va+len) with permissions 'perm | PTE_U | PTE_P'.
// If it can, then the function simply returns.
// If it cannot, 'env' is destroyed and, if env is the current
// environment, this function will not return.
//
void
user_mem_assert(struct Env *env, const void *va, size_t len, int perm)
{
	if (user_mem_check(env, va, len, perm | PTE_U) < 0) {
		cprintf("[%08x] user_mem_check assertion failure for "
			"va %08x\n", env->env_id, user_mem_check_addr);
		env_destroy(env);	// may not return
	}
}


// --------------------------------------------------------------
// Checking functions.
// --------------------------------------------------------------

//
// Check that the pages on the page_free_list are reasonable.
//
static void
check_page_free_list(bool only_low_memory)
{
	struct PageInfo *pp;
	unsigned pdx_limit = only_low_memory ? 1 : NPDENTRIES;
	int nfree_basemem = 0, nfree_extmem = 0;
	char *first_free_page;

	if (!page_free_list)
		panic("'page_free_list' is a null pointer!");

	if (only_low_memory) {
		// Move pages with lower addresses first in the free
		// list, since entry_pgdir does not map all pages.
		struct PageInfo *pp1, *pp2;
		struct PageInfo **tp[2] = { &pp1, &pp2 };
		for (pp = page_free_list; pp; pp = pp->pp_link) {
			int pagetype = PDX(page2pa(pp)) >= pdx_limit;
			*tp[pagetype] = pp;
			tp[pagetype] = &pp->pp_link;
		}
		*tp[1] = 0;
		*tp[0] = pp2;
		page_free_list = pp1;
	}

	// if there's a page that shouldn't be on the free list,
	// try to make sure it eventually causes trouble.
	for (pp = page_free_list; pp; pp = pp->pp_link)
		if (PDX(page2pa(pp)) < pdx_limit)
			memset(page2kva(pp), 0x97, 128);

	first_free_page = (char *) boot_alloc(0);
	for (pp = page_free_list; pp; pp = pp->pp_link) {
		// check that we didn't corrupt the free list itself
		assert(pp >= pages);
		assert(pp < pages + npages);
		assert(((char *) pp - (char *) pages) % sizeof(*pp) == 0);

		// check a few pages that shouldn't be on the free list
		assert(page2pa(pp) != 0);
		assert(page2pa(pp) != IOPHYSMEM);
		assert(page2pa(pp) != EXTPHYSMEM - PGSIZE);
		assert(page2pa(pp) != EXTPHYSMEM);
		assert(page2pa(pp) < EXTPHYSMEM || (char *) page2kva(pp) >= first_free_page);

		if (page2pa(pp) < EXTPHYSMEM)
			++nfree_basemem;
		else
			++nfree_extmem;
	}

	assert(nfree_basemem > 0);
	assert(nfree_extmem > 0);

	cprintf("check_page_free_list() succeeded!\n");
}

//
// Check the physical page allocator (page_alloc(), page_free(),
// and page_init()).
//
static void
check_page_alloc(void)
{
	struct PageInfo *pp, *pp0, *pp1, *pp2;
	int nfree;
	struct PageInfo *fl;
	char *c;
	int i;

	if (!pages)
		panic("'pages' is a null pointer!");

	// check number of free pages
	for (pp = page_free_list, nfree = 0; pp; pp = pp->pp_link)
		++nfree;

	// should be able to allocate three pages
	pp0 = pp1 = pp2 = 0;
	assert((pp0 = page_alloc(0)));
	assert((pp1 = page_alloc(0)));
	assert((pp2 = page_alloc(0)));

	assert(pp0);
	assert(pp1 && pp1 != pp0);
	assert(pp2 && pp2 != pp1 && pp2 != pp0);
	assert(page2pa(pp0) < npages*PGSIZE);
	assert(page2pa(pp1) < npages*PGSIZE);
	assert(page2pa(pp2) < npages*PGSIZE);

	// temporarily steal the rest of the free pages
	fl = page_free_list;
	page_free_list = 0;

	// should be no free memory
	assert(!page_alloc(0));

	// free and re-allocate?
	page_free(pp0);
	page_free(pp1);
	page_free(pp2);
	pp0 = pp1 = pp2 = 0;
	assert((pp0 = page_alloc(0)));
	assert((pp1 = page_alloc(0)));
	assert((pp2 = page_alloc(0)));
	assert(pp0);
	assert(pp1 && pp1 != pp0);
	assert(pp2 && pp2 != pp1 && pp2 != pp0);
	assert(!page_alloc(0));

	// test flags
	memset(page2kva(pp0), 1, PGSIZE);
	page_free(pp0);
	assert((pp = page_alloc(ALLOC_ZERO)));
	assert(pp && pp0 == pp);
	c = page2kva(pp);
	for (i = 0; i < PGSIZE; i++)
		assert(c[i] == 0);

	// give free list back
	page_free_list = fl;

	// free the pages we took
	page_free(pp0);
	page_free(pp1);
	page_free(pp2);

	// number of free pages should be the same
	for (pp = page_free_list; pp; pp = pp->pp_link)
		--nfree;
	assert(nfree == 0);

	cprintf("check_page_alloc() succeeded!\n");
}

//
// Checks that the kernel part of virtual address space
// has been set up roughly correctly (by mem_init()).
//
// This function doesn't test every corner case,
// but it is a pretty good sanity check.
//

static void
check_kern_pgdir(void)
{
	uint32_t i, n;
	pde_t *pgdir;

	pgdir = kern_pgdir;

	// check pages array
	n = ROUNDUP(npages*sizeof(struct PageInfo), PGSIZE);
	for (i = 0; i < n; i += PGSIZE)
		assert(check_va2pa(pgdir, UPAGES + i) == PADDR(pages) + i);

	// check envs array (new test for lab 3)
	n = ROUNDUP(NENV*sizeof(struct Env), PGSIZE);
	for (i = 0; i < n; i += PGSIZE)
		assert(check_va2pa(pgdir, UENVS + i) == PADDR(envs) + i);

	// check phys mem
	for (i = 0; i < npages * PGSIZE; i += PGSIZE)
		assert(check_va2pa(pgdir, KERNBASE + i) == i);

	// check kernel stack
	for (i = 0; i < KSTKSIZE; i += PGSIZE)
		assert(check_va2pa(pgdir, KSTACKTOP - KSTKSIZE + i) == PADDR(bootstack) + i);
	assert(check_va2pa(pgdir, KSTACKTOP - PTSIZE) == ~0);

	// check PDE permissions
	for (i = 0; i < NPDENTRIES; i++) {
		switch (i) {
		case PDX(UVPT):
		case PDX(KSTACKTOP-1):
		case PDX(UPAGES):
		case PDX(UENVS):
			assert(pgdir[i] & PTE_P);
			break;
		default:
			if (i >= PDX(KERNBASE)) {
				assert(pgdir[i] & PTE_P);
				assert(pgdir[i] & PTE_W);
			} else
				assert(pgdir[i] == 0);
			break;
		}
	}
	cprintf("check_kern_pgdir() succeeded!\n");
}

// This function returns the physical address of the page containing 'va',
// defined by the page directory 'pgdir'.  The hardware normally performs
// this functionality for us!  We define our own version to help check
// the check_kern_pgdir() function; it shouldn't be used elsewhere.

static physaddr_t
check_va2pa(pde_t *pgdir, uintptr_t va)
{
	pte_t *p;

	pgdir = &pgdir[PDX(va)];
	if (!(*pgdir & PTE_P))
		return ~0;
	p = (pte_t*) KADDR(PTE_ADDR(*pgdir));
	if (!(p[PTX(va)] & PTE_P))
		return ~0;
	return PTE_ADDR(p[PTX(va)]);
}


static void
check_page(void)
{
	struct PageInfo *pp, *pp0, *pp1, *pp2;
	struct PageInfo *fl;
	pte_t *ptep, *ptep1;
	void *va;
	int i;
	extern pde_t entry_pgdir[];

    // cprintf("BEFORE ALLOCATING 3 PAGES:   here is page_free_list: %p and its value: %p, and its pp_link: %p\n\n", page_free_list, *page_free_list, page_free_list->pp_link);
	// should be able to allocate three pages
	pp0 = pp1 = pp2 = 0;
	assert((pp0 = page_alloc(0)));
	assert((pp1 = page_alloc(0)));
	assert((pp2 = page_alloc(0)));

    // cprintf("pp0 & *pp0 & pp0->pp_ref & pp0->pp_link:  %p, %p, %d, %p\n", pp0, *pp0, pp0->pp_ref, pp0->pp_link);
    // cprintf("pp1 & *pp1 & pp1->pp_ref & pp1->pp_link:  %p, %p, %d, %p\n", pp1, *pp1, pp1->pp_ref, pp1->pp_link);
    // cprintf("pp2 & *pp2 & pp2->pp_ref & pp2->pp_link:  %p, %p, %d, %p\n\n", pp2, *pp2, pp2->pp_ref, pp2->pp_link);

	assert(pp0);
	assert(pp1 && pp1 != pp0);
	assert(pp2 && pp2 != pp1 && pp2 != pp0);

    // cprintf("JUST ALLOCATED 3 PAGES:   here is page_free_list: %p and its value: %p, and its pp_link: %p\n\n", page_free_list, *page_free_list, page_free_list->pp_link);
	// temporarily steal the rest of the free pages
	fl = page_free_list;
	page_free_list = 0;

    // cprintf("PAGE_FREE_LIST JUST SET TO 0:   here is page_free_list: %p and its value: %p, and its pp_link: %p\n\n", page_free_list, *page_free_list, page_free_list->pp_link);
	// should be no free memory
	assert(!page_alloc(0));

	// there is no page allocated at address 0
	assert(page_lookup(kern_pgdir, (void *) 0x0, &ptep) == NULL);

	// there is no free memory, so we can't allocate a page table
    // cprintf("pp1 HAS JUST BEEN INSERTED BUT SHOULD FAIL:   here is page_free_list: %p and its value: %p, and its pp_link: %p\n\n", page_free_list, *page_free_list, page_free_list->pp_link);
	assert(page_insert(kern_pgdir, pp1, 0x0, PTE_W) < 0);

	// free pp0 and try again: pp0 should be used for page table
    // this gives the page to the page_free_list
	page_free(pp0);


    //cprintf("pp0 & *pp0 & pp0->pp_ref & pp0->pp_link:  %p, %p, %d, %p\n", pp0, *pp0, pp0->pp_ref, pp0->pp_link);
    //cprintf("pp1 & *pp1 & pp1->pp_ref & pp1->pp_link:  %p, %p, %d, %p\n", pp1, *pp1, pp1->pp_ref, pp1->pp_link);
    //cprintf("pp2 & *pp2 & pp2->pp_ref & pp2->pp_link:  %p, %p, %d, %p\n\n", pp2, *pp2, pp2->pp_ref, pp2->pp_link);


    //cprintf("pp0 HAS JUST BEEN FREED, THERE SHOULD BE 1 PAGE:   here is page_free_list: %p and its value: %p, and its pp_link: %p\n\n", page_free_list, *page_free_list, page_free_list->pp_link);
	assert(page_insert(kern_pgdir, pp1, 0x0, PTE_W) == 0);
    //cprintf("pp0 & *pp0 & pp0->pp_ref & pp0->pp_link:  %p, %p, %d, %p\n", pp0, *pp0, pp0->pp_ref, pp0->pp_link);
    //cprintf("pp1 & *pp1 & pp1->pp_ref & pp1->pp_link:  %p, %p, %d, %p\n", pp1, *pp1, pp1->pp_ref, pp1->pp_link);
    //cprintf("pp2 & *pp2 & pp2->pp_ref & pp2->pp_link:  %p, %p, %d, %p\n\n", pp2, *pp2, pp2->pp_ref, pp2->pp_link);
    //cprintf("pp1 HAS JUST BEEN INSERTED AND SHOULD SUCCEED:   here is page_free_list: %p and its value: %p, and its pp_link: %p\n\n", page_free_list, *page_free_list, page_free_list->pp_link);
	assert(PTE_ADDR(kern_pgdir[0]) == page2pa(pp0));
	assert(check_va2pa(kern_pgdir, 0x0) == page2pa(pp1));
	assert(pp1->pp_ref == 1);
	assert(pp0->pp_ref == 1);

	// should be able to map pp2 at PGSIZE because pp0 is already allocated for page table
	assert(page_insert(kern_pgdir, pp2, (void*) PGSIZE, PTE_W) == 0);
    //cprintf("pp0 & *pp0 & pp0->pp_ref & pp0->pp_link:  %p, %p, %d, %p\n", pp0, *pp0, pp0->pp_ref, pp0->pp_link);
    //cprintf("pp1 & *pp1 & pp1->pp_ref & pp1->pp_link:  %p, %p, %d, %p\n", pp1, *pp1, pp1->pp_ref, pp1->pp_link);
    //cprintf("pp2 & *pp2 & pp2->pp_ref & pp2->pp_link:  %p, %p, %d, %p\n\n", pp2, *pp2, pp2->pp_ref, pp2->pp_link);
    //cprintf("pp2 HAS JUST BEEN INSERTED at 0x1000 AND SHOULD SUCCEED:   here is page_free_list: %p and its value: %p, and its pp_link: %p\n\n", page_free_list, *page_free_list, page_free_list->pp_link);
	assert(check_va2pa(kern_pgdir, PGSIZE) == page2pa(pp2));
	assert(pp2->pp_ref == 1);


    // cprintf("END OF PAGE_INIT:   here is page_free_list: %p and its value: %p, and its pp_link: %p\n\n", page_free_list, *page_free_list, page_free_list->pp_link);
    // cprintf("here is pp0: %p, and the values at its pp_ref: %d, and its pp_link: %p\n\n", pp0, pp0->pp_ref, pp0->pp_link);
    // cprintf("END OF PAGE_INIT:   here is page_free_list: %p and its value: %p, and its pp_link: %p\n\n", page_free_list, *page_free_list, page_free_list->pp_link);
    // cprintf("here is pp1: %p, and the values at its pp_ref: %d, and its pp_link: %p\n\n", pp1, pp1->pp_ref, pp1->pp_link);
    // cprintf("END OF PAGE_INIT:   here is page_free_list: %p and its value: %p, and its pp_link: %p\n\n", page_free_list, *page_free_list, page_free_list->pp_link);
    // cprintf("here is pp2: %p, and the values at its pp_ref: %d, and its pp_link: %p\n\n", pp2, pp2->pp_ref, pp2->pp_link);
    //cprintf("END OF PAGE_INIT:   here is page_free_list: %p and its value: %p, and its pp_link: %p\n\n", page_free_list, *page_free_list, page_free_list->pp_link);

	// should be no free memory
	assert(!page_alloc(0));

	// should be able to map pp2 at PGSIZE because it's already there
	assert(page_insert(kern_pgdir, pp2, (void*) PGSIZE, PTE_W) == 0);
    //cprintf("pp0 & *pp0 & pp0->pp_ref & pp0->pp_link:  %p, %p, %d, %p\n", pp0, *pp0, pp0->pp_ref, pp0->pp_link);
    //cprintf("pp1 & *pp1 & pp1->pp_ref & pp1->pp_link:  %p, %p, %d, %p\n", pp1, *pp1, pp1->pp_ref, pp1->pp_link);
    //cprintf("pp2 & *pp2 & pp2->pp_ref & pp2->pp_link:  %p, %p, %d, %p\n\n", pp2, *pp2, pp2->pp_ref, pp2->pp_link);
	assert(check_va2pa(kern_pgdir, PGSIZE) == page2pa(pp2));
	assert(pp2->pp_ref == 1);

	// pp2 should NOT be on the free list
	// could happen in ref counts are handled sloppily in page_insert
	assert(!page_alloc(0));

	// check that pgdir_walk returns a pointer to the pte
	ptep = (pte_t *) KADDR(PTE_ADDR(kern_pgdir[PDX(PGSIZE)]));
	assert(pgdir_walk(kern_pgdir, (void*)PGSIZE, 0) == ptep+PTX(PGSIZE));

	// should be able to change permissions too.
	assert(page_insert(kern_pgdir, pp2, (void*) PGSIZE, PTE_W|PTE_U) == 0);
	assert(check_va2pa(kern_pgdir, PGSIZE) == page2pa(pp2));
	assert(pp2->pp_ref == 1);
	assert(*pgdir_walk(kern_pgdir, (void*) PGSIZE, 0) & PTE_U);
	assert(kern_pgdir[0] & PTE_U);

	// should be able to remap with fewer permissions
	assert(page_insert(kern_pgdir, pp2, (void*) PGSIZE, PTE_W) == 0);
	assert(*pgdir_walk(kern_pgdir, (void*) PGSIZE, 0) & PTE_W);
	assert(!(*pgdir_walk(kern_pgdir, (void*) PGSIZE, 0) & PTE_U));

	// should not be able to map at PTSIZE because need free page for page table
	assert(page_insert(kern_pgdir, pp0, (void*) PTSIZE, PTE_W) < 0);

	// insert pp1 at PGSIZE (replacing pp2)
    //cprintf("pp1 now replacing pp2 via page_insert");
	assert(page_insert(kern_pgdir, pp1, (void*) PGSIZE, PTE_W) == 0);
	assert(!(*pgdir_walk(kern_pgdir, (void*) PGSIZE, 0) & PTE_U));

	// should have pp1 at both 0 and PGSIZE, pp2 nowhere, ...
	assert(check_va2pa(kern_pgdir, 0) == page2pa(pp1));
	assert(check_va2pa(kern_pgdir, PGSIZE) == page2pa(pp1));
	// ... and ref counts should reflect this
    //cprintf("pp0 & *pp0 & pp0->pp_ref & pp0->pp_link:  %p, %p, %d, %p\n", pp0, *pp0, pp0->pp_ref, pp0->pp_link);
    //cprintf("pp1 & *pp1 & pp1->pp_ref & pp1->pp_link:  %p, %p, %d, %p\n", pp1, *pp1, pp1->pp_ref, pp1->pp_link);
    //cprintf("pp2 & *pp2 & pp2->pp_ref & pp2->pp_link:  %p, %p, %d, %p\n\n", pp2, *pp2, pp2->pp_ref, pp2->pp_link);
	assert(pp1->pp_ref == 2);
	assert(pp2->pp_ref == 0);

	// pp2 should be returned by page_alloc
	assert((pp = page_alloc(0)) && pp == pp2);

	// unmapping pp1 at 0 should keep pp1 at PGSIZE
	page_remove(kern_pgdir, 0x0);
	assert(check_va2pa(kern_pgdir, 0x0) == ~0);
	assert(check_va2pa(kern_pgdir, PGSIZE) == page2pa(pp1));
	assert(pp1->pp_ref == 1);
	assert(pp2->pp_ref == 0);

	// test re-inserting pp1 at PGSIZE
	assert(page_insert(kern_pgdir, pp1, (void*) PGSIZE, 0) == 0);
	assert(pp1->pp_ref);
	assert(pp1->pp_link == NULL);

	// unmapping pp1 at PGSIZE should free it
	page_remove(kern_pgdir, (void*) PGSIZE);
	assert(check_va2pa(kern_pgdir, 0x0) == ~0);
	assert(check_va2pa(kern_pgdir, PGSIZE) == ~0);
	assert(pp1->pp_ref == 0);
	assert(pp2->pp_ref == 0);

	// so it should be returned by page_alloc
	assert((pp = page_alloc(0)) && pp == pp1);

	// should be no free memory
	assert(!page_alloc(0));

	// forcibly take pp0 back
	assert(PTE_ADDR(kern_pgdir[0]) == page2pa(pp0));
	kern_pgdir[0] = 0;
	assert(pp0->pp_ref == 1);
	pp0->pp_ref = 0;

	// check pointer arithmetic in pgdir_walk
	page_free(pp0);
	va = (void*)(PGSIZE * NPDENTRIES + PGSIZE);
	ptep = pgdir_walk(kern_pgdir, va, 1);
	ptep1 = (pte_t *) KADDR(PTE_ADDR(kern_pgdir[PDX(va)]));
	assert(ptep == ptep1 + PTX(va));
	kern_pgdir[PDX(va)] = 0;
	pp0->pp_ref = 0;

	// check that new page tables get cleared
	memset(page2kva(pp0), 0xFF, PGSIZE);
	page_free(pp0);
	pgdir_walk(kern_pgdir, 0x0, 1);
	ptep = (pte_t *) page2kva(pp0);
	for(i=0; i<NPTENTRIES; i++)
		assert((ptep[i] & PTE_P) == 0);
	kern_pgdir[0] = 0;
	pp0->pp_ref = 0;

	// give free list back
	page_free_list = fl;

	// free the pages we took
	page_free(pp0);
	page_free(pp1);
	page_free(pp2);

	cprintf("check_page() succeeded!\n");
}

// check page_insert, page_remove, &c, with an installed kern_pgdir
static void
check_page_installed_pgdir(void)
{
	struct PageInfo *pp, *pp0, *pp1, *pp2;
	struct PageInfo *fl;
	pte_t *ptep, *ptep1;
	uintptr_t va;
	int i;

	// check that we can read and write installed pages
	pp1 = pp2 = 0;
	assert((pp0 = page_alloc(0)));
	assert((pp1 = page_alloc(0)));
	assert((pp2 = page_alloc(0)));
	page_free(pp0);
	memset(page2kva(pp1), 1, PGSIZE);
	memset(page2kva(pp2), 2, PGSIZE);
	page_insert(kern_pgdir, pp1, (void*) PGSIZE, PTE_W);
	assert(pp1->pp_ref == 1);
	assert(*(uint32_t *)PGSIZE == 0x01010101U);
	page_insert(kern_pgdir, pp2, (void*) PGSIZE, PTE_W);
	assert(*(uint32_t *)PGSIZE == 0x02020202U);
	assert(pp2->pp_ref == 1);
	assert(pp1->pp_ref == 0);
	*(uint32_t *)PGSIZE = 0x03030303U;
	assert(*(uint32_t *)page2kva(pp2) == 0x03030303U);
	page_remove(kern_pgdir, (void*) PGSIZE);
	assert(pp2->pp_ref == 0);

	// forcibly take pp0 back
	assert(PTE_ADDR(kern_pgdir[0]) == page2pa(pp0));
	kern_pgdir[0] = 0;
	assert(pp0->pp_ref == 1);
	pp0->pp_ref = 0;

	// free the pages we took
	page_free(pp0);

	cprintf("check_page_installed_pgdir() succeeded!\n");
}
